"""Build the official expert layout with one Skill and a local HTTP MCP dependency."""
from pathlib import Path
from zipfile import ZipFile, ZipInfo, ZIP_DEFLATED
import hashlib
import json
import re
import struct

root = Path(__file__).resolve().parent.parent
version = json.loads((root / 'package.json').read_text())['version']
source = root / 'packaging/expert'
entries = {}

def add(name, path):
    assert not path.is_symlink() and path.is_file(), path
    assert name not in entries
    assert not any(p in {'.data', '.git', 'node_modules', '.DS_Store'} or p.startswith('._') for p in Path(name).parts)
    entries[name] = path.read_bytes()

def add_json(name, value):
    entries[name] = (json.dumps(value, ensure_ascii=False, indent=2) + '\n').encode()

prompts = [
    {'zh': '帮我创建一份销售分析表，添加公式和图表，并预览草稿。', 'en': 'Create a sales analysis spreadsheet with formulas and a chart, then preview the draft.'},
    {'zh': '把项目说明整理成文档和演示文稿，完成后交给我审阅。', 'en': 'Turn the project brief into a document and a presentation for my review.'},
    {'zh': '查看这份办公文件的修改，对比差异，等我确认后再合入。', 'en': 'Compare the changes in this Office file and wait for my approval before merging.'},
]
plugin = {
    'name': 'univer-office', 'version': version, 'expertType': 'agent', 'agentName': 'univer-office',
    'description': 'Create, analyze, review and export local Office content with the Univer Office MCP service.',
    'author': {'name': 'dream-num', 'email': 'liuyang@univer.ai'},
    'agents': ['./agents/univer-office.md'], 'skills': ['./skills/univer-office'],
    'displayName': {'zh': 'Univer Office 办公专家', 'en': 'Univer Office'},
    'profession': {'zh': '办公内容专家', 'en': 'Office Content Specialist'},
    'displayDescription': {
        'zh': '创建和分析表格、文档、幻灯片、多维表格与白板，支持内容预览、版本对比、人工审阅和文件导出。',
        'en': 'Create and analyze spreadsheets, documents, slides, Base tables and Board canvases with previews, comparisons, human review and exports. Requires a running local Office service; development preview.',
    },
    'avatar': 'avatars/univer-office.png', 'categoryId': '04-DataAI',
    'defaultInitPrompt': prompts[0], 'plugin': 'univer-office',
    'tags': [{'zh': '办公内容', 'en': 'Office Content'}, {'zh': '数据分析', 'en': 'Data Analysis'}, {'zh': '修改审阅', 'en': 'Change Review'}],
    'quickPrompts': prompts, 'dependencies': {'mcpServers': './.mcp.json'},
    'homepage': 'https://github.com/dream-num/workbuddy-univer-office', 'license': 'Apache-2.0',
    'keywords': ['univer', 'office', 'spreadsheet', 'document', 'presentation'],
}
add_json('.codebuddy-plugin/plugin.json', plugin)
add_json('.mcp.json', {'mcpServers': {'univer-office': {
    'type': 'http', 'url': 'http://127.0.0.1:9080/mcp',
    'headers': {'Authorization': 'Bearer ${UNIVER_OFFICE_TOKEN}'},
    'x-workbuddy': {
        'displayName': {'zh': 'Univer Office', 'en': 'Univer Office'},
        'description': {'zh': '先按包内 README 启动本地 Office 服务，再填写连接令牌。', 'en': 'Start the local Office service using the bundled README, then enter its connection token.'},
        'icon': './avatars/univer-office.png',
        'auth': {'type': 'token', 'tokenSchema': {
            'title': {'zh': '连接本地 Univer Office', 'en': 'Connect local Univer Office'},
            'description': {'zh': '输入本地服务生成的令牌，不含 Bearer 前缀；服务重启后需要更新。', 'en': 'Enter the token generated by your local service without the Bearer prefix. Update it after restarting the service.'},
            'fields': [{'key': 'UNIVER_OFFICE_TOKEN', 'label': {'zh': 'Office 连接令牌', 'en': 'Office connection token'}, 'type': 'password', 'required': True}],
        }},
    },
}}})
add('agents/univer-office.md', source / 'agents/univer-office.md')
add('avatars/univer-office.png', source / 'avatar.png')
add('README.md', source / 'README.md')
add('LICENSE', root / 'LICENSE')
for path in sorted((root / 'skills/univer-office').rglob('*')):
    assert not path.is_symlink(), path
    if path.is_file():
        assert path.suffix == '.md', path
        add(path.relative_to(root).as_posix(), path)

# Reuse the runtime packager's explicit audited whitelist, never crawl local data.
audit = json.loads((root / '.data/packages/package-audit.json').read_text())
assert audit['version'] == version
for name in audit['files']:
    if name.startswith(('dist/', 'config/')) or name in {'package.json', 'pnpm-lock.yaml', 'assets/univer-office.png'}:
        add('runtime/' + name, root / name)

assert 40 <= len(plugin['displayDescription']['zh']) <= 50
assert plugin['defaultInitPrompt'] == plugin['quickPrompts'][0]
assert len(plugin['tags']) == len(plugin['quickPrompts']) == 3
assert sorted(n for n in entries if n.endswith('/SKILL.md')) == ['skills/univer-office/SKILL.md']
assert len([n for n in entries if n.startswith('skills/univer-office/references/')]) == 7
for name in [plugin['avatar'], *plugin['agents'], plugin['dependencies']['mcpServers']]:
    assert name.removeprefix('./') in entries, name
for required in ['runtime/dist/mcp/http.js', 'runtime/dist/viewer/index.html', 'runtime/dist/mcp-app/index.html', 'runtime/config/registry.npmrc']:
    assert required in entries, required
png = entries[plugin['avatar']]
assert png[:8] == b'\x89PNG\r\n\x1a\n' and struct.unpack('>II', png[16:24]) == (512, 512)
assert len(png) < 500 * 1024
agent = entries['agents/univer-office.md'].decode()
assert not re.search(r'^tools:', agent, re.M)
for name, value in entries.items():
    if name.endswith(('.md', '.json', '.js', '.html', '.yaml', '.npmrc')):
        assert not re.search(rb'/Users/|/home/[^/\s]+/|Bearer [a-f0-9]{64}', value), name

output = root / '.data/packages'
archive = output / f'univer-office-expert-{version}.zip'
temporary = archive.with_suffix('.zip.tmp')
with ZipFile(temporary, 'w', ZIP_DEFLATED) as zipped:
    for name, data in sorted(entries.items()):
        info = ZipInfo(name, (2026, 1, 1, 0, 0, 0))
        info.compress_type = ZIP_DEFLATED
        info.external_attr = 0o100644 << 16
        zipped.writestr(info, data)
with ZipFile(temporary) as zipped:
    assert sorted(zipped.namelist()) == sorted(entries)
    assert zipped.testzip() is None
    for name, data in entries.items():
        assert zipped.read(name) == data
temporary.replace(archive)
report = {'archive': archive.name, 'bytes': archive.stat().st_size, 'sha256': hashlib.sha256(archive.read_bytes()).hexdigest(), 'files': sorted(entries), 'experts': 1, 'skills': 1, 'mcpServers': 1, 'platformUploadVerified': False, 'automaticRuntimeInstallation': False}
(output / 'expert-package-audit.json').write_text(json.dumps(report, indent=2) + '\n')
print(json.dumps({k: v for k, v in report.items() if k != 'files'}))
